[package]
name = "draw-together"
version = "2.2.2"
edition = "2021"

[[bin]]
name = "draw-together"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.10.0", features = ["full"] }
axum = { version = "0.8.1", features = ["ws"] }
futures-util = "0.3.31"
